version: '3'
services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: vendorsite
      MYSQL_ALLOW_EMPTY_PASSWORD: "true"
    ports:
      - "3306:3306"
    volumes:
      - ./db/dumpVendorsite.sql:/docker-entrypoint-initdb.d/dumpVendorsite.sql
      - db_data:/var/lib/mysql  # Create a volume for the database

  backend:
    build:
      context: ./backend
    volumes:
      - ./backend:/app
    depends_on:
      - db
    command: ["tail", "-f", "/dev/null"]  # Keep the container running

  frontend:
    build:
      context: vendorsite
      target: builder
    ports:
      - 4200:4200
    volumes:
      - ./vendorsite:/project
      - /project/node_modules
    depends_on:
      - backend  # Ensure backend is started before frontend

volumes:
  db_data:  # Define a named volume for the database data
